[project]
name = "kubernetes-virtual-cluster"
version = "0.1.0"
description = "Kubernetes Virtual Cluster"
authors = [
    {name = "Hoplin", email = "hoplin.dev@gmail.com"}
]

[tool.setuptools]
packages = ["kluster"]
